### ISSUE TITLE
952.json (tower of zot) Path - No treasure chest looting

### ISSUE THREAD

**Issue by ShadowCid** [ffxivcode/DalamudPlugins#2]
["-17.495144, -469.73303, 102.95347","67.43335, -460.73337, -0.63435876","68.494026, -444.0335, -41.699265","Boss|68.44621, -442.9678, -124.525665","68.43963, -442.96777, -136.7104","63.70522, -443.4718, -176.92865","62.511047, -441.8648, -183.03806","Wait|5000","-299.3411, -184.96202, 179.30586","-306.7743, -184.77913, 140.85793","-340.93405, -180.9656, 96.32849","-292.33026, -176.21986, 71.34034","-239.41109, -171.95277, 78.36588","-258.09778, -167.68823, 12.265202","Boss|-257.84656, -169.00002, -26.224638","-260.15854, -167.76633, -80.5537","-263.86606, -166.38579, -92.27521","Wait|5000","-16.762384, 538.2506, -138.16895","-105.07814, 541.671, -50.9927","-66.509186, 545.219, -13.893278","Boss|-28.373354, 546.10394, -48.74818","-23.969618, 546.104, -53.568314","-19.12543, 546.104, -58.097897","ExitDuty|"]

**Comment by adambennett55** [comment]
Added
