### ISSUE TITLE
822 Path - Mt Gulg

### ISSUE THREAD

**Issue by ShadowCid** [ffxivcode/DalamudPlugins#3]
["304.8271, -78.60709, 77.899025","337.63907, -82.03888, 7.3534465","337.55545, -76.84974, -42.038593","344.3003, -59.91755, -141.13329","312.6997, -53.77352, -163.42107","Boss|185.26382, -48.000004, -170.35974","170.22514, -48, -169.95364","TreasureCoffer|","101.66689, -46.661625, -199.22783","-4.5072765, -31, -196.24428","-38.17845, -23.52053, -198.61458","Wait|5000","-85.09147, 174.8378, -233.6684","-130.14206, 192.42393, -178.28888","-199.4669, 202.04999, -108.73894","-239.2851, 201.99959, -98.554276","TreasureCoffer|","Boss|-239.98972, 210, -46.359756","-240.1165, 210, -39.97446","TreasureCoffer|","-288.28586, 194, 41.170097","-288.12585, 194, 86.62224","TreasureCoffer|","-191.51337, 194, 99.35413","-253.9688, 202, 139.79968","TreasureCoffer|","-240.62009, 204.3701, 166.2764","-240.08275, 204.3701, 183.21916","Boss|-239.76259, 210, 242.16539","-240.2041, 210, 246.0468","TreasureCoffer|","ExitDuty|"]

**Comment by adambennett55** [comment]
Implemented
